UserAuthApp/urls.py
from django.contrib import admin
from django.urls import include, path
from basicUserAuthApp import views
urlpatterns = [
    path('',views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basicUserAuthApp/', include('basicUserAuthApp.urls')),
    path('logout/',views.user_logout, name='logout'),
]

basicUserAuthApp/urls.py
from django.urls import path
from basicUserAuthApp import views
app_name = 'basicUserAuthApp'
urlpatterns = [
    path('login/',views.login_page, name='login_page'),
    path('registration/',views.registration, name='registration'),
    path('log_in/',views.log_in, name='log_in'),
    path('register/',views.register, name='register'),
    path('user_page/',views.user_page, name='user'),
]

basicUserAuthApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

basicUserAuthApp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from basicUserAuthApp.models import User
# Create your views here.
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def index(request):
    return render(request,'basicUserAuthApp/index.html')
def login_page(request):
    return render(request,'basicUserAuthApp/login.html')
def registration(request):
    return render(request,'basicUserAuthApp/registration.html')
def user_page(request):
    return render(request,'basicUserAuthApp/user.html')
def log_in(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(f"Input Username:{username}")
        user = authenticate(username = username,password = password)
        if user:
            print("User is authenticated.")
            if user.is_active:
                print("User is active.")
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse(f"{username} account is not active")
        else:
            print("Someone tried to login, but fortunantly failed!")
            print(f"Username: {username}")
            return HttpResponse("Login is failed!")
    print(username)
    return index(request)

def register(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        reset_password = request.POST.get('rest_password')
        if password == reset_password:
            user = User.objects.create_user(username,email,password)
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            if user :
                print("User is registered!")
                print(f"User:{user}")
        else:
            return HttpResponse("Password typed differently!")
    print(f"Input First_name:{first_name}")
    print(f"Input Last_name:{last_name}")
    print(f"Input Username:{username}")
    print(f"Input Email:{email}")
    print(f"Status password{password == reset_password}")
    return index(request)

templates/basicUserAuthApp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>User Authentication Application - Base page!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">UserAuthApp</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basicUserAuthApp:registration' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basicUserAuthApp:login_page' %}">Login</a>
          </li>
          {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basicUserAuthApp:user' %}">Hello, {{user.username}}</a>
          </li>
        </ul>
        {% endif %}
      </div>
    </nav>
    {% block body_block %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/basicUserAuthApp/index.html
<!DOCTYPE html>
{% extends "basicUserAuthApp/base.html" %}
{% block body_block %}
<div class="container">
  <div class="text-center">
    <br>
    <h1 class="">Welcome to User Authentication Application Main Page!</h1>
  </div>
</div>
{% endblock %}

templates/basicUserAuthApp/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>User Authentication: Login Page</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body>
<form class="box" action="{% url 'basicUserAuthApp:log_in' %}" method="post">
<h1>Login</h1>
{% csrf_token %}
<input type="text" name="username" placeholder="Username">
<input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
<a href="{% url 'index'%}">Back to Main Page</a>
</form>
  </body>
</html>

templates/basicUserAuthApp/registration.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>User Authentication: Registration Page</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body>
<form class="box" action="{% url 'basicUserAuthApp:register' %}" method="post">
<h1>Registration</h1>
{% csrf_token %}
<input type="text" name="first_name" placeholder="First Name">
<input type="text" name="last_name" placeholder="Last Name">
<input type="text" name="username" placeholder="Username">
<input type="text" name="email" placeholder=".@mail.com">
<input type="password" name="password" placeholder="Password">
<input type="password" name="rest_password" placeholder="Reset Password">
<input type="submit" name="" value="Register">
<a href="{% url 'index'%}">Back to Main Page</a>
</form>
  </body>
</html>

templates/basicUserAuthApp/user.html
<!DOCTYPE html>
{% extends "basicUserAuthApp/base.html" %}
{% block body_block %}
<br>
<div class="container">
<h4>First name: {{user.first_name}}</h4>
<h4>Last name: {{user.last_name}}</h4>
<h4>Username: {{user.username}}</h4>
<h4>Email: {{user.email}}</h4>
</div>
{% endblock %}